version: '3'
services:
  workflowdefservice:
    image: gcr.io/sap-se-commerce-arch/workflowdefservice:latest
    restart: always
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017
      - DB_NAME=swell
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - /private/var/lib/mongo:/data/db
    ports:
      - "27017:27017"