version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - /private/var/lib/mongo:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:management
    restart: always
    volumes:
      - /private/var/lib/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  workflowservice:
    image: swell-workflowservice:latest
    restart: always
    environment:
      - DB_URI=mongodb://mongo:27017
      - MESSAGING_URI=amqp://guest:guest@rabbitmq:5672/
      - PORT=3000
    ports:
      - "3000:3000"
    links:
      - mongo
      - rabbitmq
    depends_on: 
      - mongo
      - rabbitmq
  actiondispatcher:
    image: swell-actiondispatcher:latest
    restart: always
    environment:
      - MESSAGING_URI=amqp://guest:guest@rabbitmq:5672/
    links:
      - rabbitmq
    depends_on: 
      - rabbitmq
    
  # actiondispatcher:
  #   image: gcr.io/sap-se-commerce-arch/actiondispatcher:latest
  #   restart: always
  #   environment:
  #     - MESSAGING_URI=amqp://guest:guest@rabbitmq:5672/
  #   links:
  #     - rabbitmq
  #   depends_on: 
  #     - rabbitmq
        